# Data Gather scratch

Let's use the very nice project [COVID19Py](https://github.com/Kamaropoulos/COVID19Py) package to get `json` file with time series for COVID-19 around the world.

In [1]:
import COVID19Py

And the we need to instantiate the parser (for example):

In [2]:
covid19 = COVID19Py.COVID19()

We have to set which database we want. In our case, we are interest in JHU database:

In [3]:
covid19 = COVID19Py.COVID19(data_source="jhu")

Now, we can get time series by country:

In [4]:
location = covid19.getLocationByCountryCode("BR", timelines=True)

location

[{'id': 28,
  'country': 'Brazil',
  'country_code': 'BR',
  'country_population': 201103330,
  'province': '',
  'last_updated': '2020-03-28T05:54:07.410382Z',
  'coordinates': {'latitude': '-14.235', 'longitude': '-51.9253'},
  'latest': {'confirmed': 3417, 'deaths': 92, 'recovered': 0},
  'timelines': {'confirmed': {'latest': 3417,
    'timeline': {'2020-01-22T00:00:00Z': 0,
     '2020-01-23T00:00:00Z': 0,
     '2020-01-24T00:00:00Z': 0,
     '2020-01-25T00:00:00Z': 0,
     '2020-01-26T00:00:00Z': 0,
     '2020-01-27T00:00:00Z': 0,
     '2020-01-28T00:00:00Z': 0,
     '2020-01-29T00:00:00Z': 0,
     '2020-01-30T00:00:00Z': 0,
     '2020-01-31T00:00:00Z': 0,
     '2020-02-01T00:00:00Z': 0,
     '2020-02-02T00:00:00Z': 0,
     '2020-02-03T00:00:00Z': 0,
     '2020-02-04T00:00:00Z': 0,
     '2020-02-05T00:00:00Z': 0,
     '2020-02-06T00:00:00Z': 0,
     '2020-02-07T00:00:00Z': 0,
     '2020-02-08T00:00:00Z': 0,
     '2020-02-09T00:00:00Z': 0,
     '2020-02-10T00:00:00Z': 0,
     '2020-02-11T00:00:00Z': 0,
     '2020-02-12T00:00:00Z': 0,
     '2020-02-13T00:00:00Z': 0,
     '2020-02-14T00:00:00Z': 0,
     '2020-02-15T00:00:00Z': 0,
     '2020-02-16T00:00:00Z': 0,
     '2020-02-17T00:00:00Z': 0,
     '2020-02-18T00:00:00Z': 0,
     '2020-02-19T00:00:00Z': 0,
     '2020-02-20T00:00:00Z': 0,
     '2020-02-21T00:00:00Z': 0,
     '2020-02-22T00:00:00Z': 0,
     '2020-02-23T00:00:00Z': 0,
     '2020-02-24T00:00:00Z': 0,
     '2020-02-25T00:00:00Z': 0,
     '2020-02-26T00:00:00Z': 1,
     '2020-02-27T00:00:00Z': 1,
     '2020-02-28T00:00:00Z': 1,
     '2020-02-29T00:00:00Z': 2,
     '2020-03-01T00:00:00Z': 2,
     '2020-03-02T00:00:00Z': 2,
     '2020-03-03T00:00:00Z': 2,
     '2020-03-04T00:00:00Z': 4,
     '2020-03-05T00:00:00Z': 4,
     '2020-03-06T00:00:00Z': 13,
     '2020-03-07T00:00:00Z': 13,
     '2020-03-08T00:00:00Z': 20,
     '2020-03-09T00:00:00Z': 25,
     '2020-03-10T00:00:00Z': 31,
     '2020-03-11T00:00:00Z': 38,
     '2020-03-12T00:00:00Z': 52,
     '2020-03-13T00:00:00Z': 151,
     '2020-03-14T00:00:00Z': 151,
     '2020-03-15T00:00:00Z': 162,
     '2020-03-16T00:00:00Z': 200,
     '2020-03-17T00:00:00Z': 321,
     '2020-03-18T00:00:00Z': 372,
     '2020-03-19T00:00:00Z': 621,
     '2020-03-20T00:00:00Z': 793,
     '2020-03-21T00:00:00Z': 1021,
     '2020-03-22T00:00:00Z': 1546,
     '2020-03-23T00:00:00Z': 1924,
     '2020-03-24T00:00:00Z': 2247,
     '2020-03-25T00:00:00Z': 2554,
     '2020-03-26T00:00:00Z': 2985,
     '2020-03-27T00:00:00Z': 3417}},
   'deaths': {'latest': 92,
    'timeline': {'2020-01-22T00:00:00Z': 0,
     '2020-01-23T00:00:00Z': 0,
     '2020-01-24T00:00:00Z': 0,
     '2020-01-25T00:00:00Z': 0,
     '2020-01-26T00:00:00Z': 0,
     '2020-01-27T00:00:00Z': 0,
     '2020-01-28T00:00:00Z': 0,
     '2020-01-29T00:00:00Z': 0,
     '2020-01-30T00:00:00Z': 0,
     '2020-01-31T00:00:00Z': 0,
     '2020-02-01T00:00:00Z': 0,
     '2020-02-02T00:00:00Z': 0,
     '2020-02-03T00:00:00Z': 0,
     '2020-02-04T00:00:00Z': 0,
     '2020-02-05T00:00:00Z': 0,
     '2020-02-06T00:00:00Z': 0,
     '2020-02-07T00:00:00Z': 0,
     '2020-02-08T00:00:00Z': 0,
     '2020-02-09T00:00:00Z': 0,
     '2020-02-10T00:00:00Z': 0,
     '2020-02-11T00:00:00Z': 0,
     '2020-02-12T00:00:00Z': 0,
     '2020-02-13T00:00:00Z': 0,
     '2020-02-14T00:00:00Z': 0,
     '2020-02-15T00:00:00Z': 0,
     '2020-02-16T00:00:00Z': 0,
     '2020-02-17T00:00:00Z': 0,
     '2020-02-18T00:00:00Z': 0,
     '2020-02-19T00:00:00Z': 0,
     '2020-02-20T00:00:00Z': 0,
     '2020-02-21T00:00:00Z': 0,
     '2020-02-22T00:00:00Z': 0,
     '2020-02-23T00:00:00Z': 0,
     '2020-02-24T00:00:00Z': 0,
     '2020-02-25T00:00:00Z': 0,
     '2020-02-26T00:00:00Z': 0,
     '2020-02-27T00:00:00Z': 0,
     '2020-02-28T00:00:00Z': 0,
     '2020-02-29T00:00:00Z': 0,
     '2020-03-01T00:00:00Z': 0,
     '2020-03-02T00:00:00Z': 0,
     '2020-03-03T00:00:00Z': 0,
     '2020-03-04T00:00:00Z': 0,
     '2020-03-05T00:00:00Z': 0,
     '2020-03-06T00:00:00Z': 0,
     '2020-03-07T00:00:00Z': 0,
     '2020-03-08T00:00:00Z': 0,
     '2020-03-09T00:00:00Z': 0,
     '2020-03-10T00:00:00Z': 0,
     '2020-03-11T00:00:00Z': 0,
     '2020-03-12T00:00:00Z': 0,
     '2020-03-13T00:00:00Z': 0,
     '2020-03-14T00:00:00Z': 0,
     '2020-03-15T00:00:00Z': 0,
     '2020-03-16T00:00:00Z': 0,
     '2020-03-17T00:00:00Z': 1,
     '2020-03-18T00:00:00Z': 3,
     '2020-03-19T00:00:00Z': 6,
     '2020-03-20T00:00:00Z': 11,
     '2020-03-21T00:00:00Z': 15,
     '2020-03-22T00:00:00Z': 25,
     '2020-03-23T00:00:00Z': 34,
     '2020-03-24T00:00:00Z': 46,
     '2020-03-25T00:00:00Z': 59,
     '2020-03-26T00:00:00Z': 77,
     '2020-03-27T00:00:00Z': 92}},
   'recovered': {'latest': 0, 'timeline': {}}}}]

The above getter method returns a list. Each entry has a `json` parsed as a Python `dict`. To get the country data, we run the following:

In [5]:
location[0]['timelines']

{'confirmed': {'latest': 3417,
  'timeline': {'2020-01-22T00:00:00Z': 0,
   '2020-01-23T00:00:00Z': 0,
   '2020-01-24T00:00:00Z': 0,
   '2020-01-25T00:00:00Z': 0,
   '2020-01-26T00:00:00Z': 0,
   '2020-01-27T00:00:00Z': 0,
   '2020-01-28T00:00:00Z': 0,
   '2020-01-29T00:00:00Z': 0,
   '2020-01-30T00:00:00Z': 0,
   '2020-01-31T00:00:00Z': 0,
   '2020-02-01T00:00:00Z': 0,
   '2020-02-02T00:00:00Z': 0,
   '2020-02-03T00:00:00Z': 0,
   '2020-02-04T00:00:00Z': 0,
   '2020-02-05T00:00:00Z': 0,
   '2020-02-06T00:00:00Z': 0,
   '2020-02-07T00:00:00Z': 0,
   '2020-02-08T00:00:00Z': 0,
   '2020-02-09T00:00:00Z': 0,
   '2020-02-10T00:00:00Z': 0,
   '2020-02-11T00:00:00Z': 0,
   '2020-02-12T00:00:00Z': 0,
   '2020-02-13T00:00:00Z': 0,
   '2020-02-14T00:00:00Z': 0,
   '2020-02-15T00:00:00Z': 0,
   '2020-02-16T00:00:00Z': 0,
   '2020-02-17T00:00:00Z': 0,
   '2020-02-18T00:00:00Z': 0,
   '2020-02-19T00:00:00Z': 0,
   '2020-02-20T00:00:00Z': 0,
   '2020-02-21T00:00:00Z': 0,
   '2020-02-22T00:00:00Z': 0,
   '2020-02-23T00:00:00Z': 0,
   '2020-02-24T00:00:00Z': 0,
   '2020-02-25T00:00:00Z': 0,
   '2020-02-26T00:00:00Z': 1,
   '2020-02-27T00:00:00Z': 1,
   '2020-02-28T00:00:00Z': 1,
   '2020-02-29T00:00:00Z': 2,
   '2020-03-01T00:00:00Z': 2,
   '2020-03-02T00:00:00Z': 2,
   '2020-03-03T00:00:00Z': 2,
   '2020-03-04T00:00:00Z': 4,
   '2020-03-05T00:00:00Z': 4,
   '2020-03-06T00:00:00Z': 13,
   '2020-03-07T00:00:00Z': 13,
   '2020-03-08T00:00:00Z': 20,
   '2020-03-09T00:00:00Z': 25,
   '2020-03-10T00:00:00Z': 31,
   '2020-03-11T00:00:00Z': 38,
   '2020-03-12T00:00:00Z': 52,
   '2020-03-13T00:00:00Z': 151,
   '2020-03-14T00:00:00Z': 151,
   '2020-03-15T00:00:00Z': 162,
   '2020-03-16T00:00:00Z': 200,
   '2020-03-17T00:00:00Z': 321,
   '2020-03-18T00:00:00Z': 372,
   '2020-03-19T00:00:00Z': 621,
   '2020-03-20T00:00:00Z': 793,
   '2020-03-21T00:00:00Z': 1021,
   '2020-03-22T00:00:00Z': 1546,
   '2020-03-23T00:00:00Z': 1924,
   '2020-03-24T00:00:00Z': 2247,
   '2020-03-25T00:00:00Z': 2554,
   '2020-03-26T00:00:00Z': 2985,
   '2020-03-27T00:00:00Z': 3417}},
 'deaths': {'latest': 92,
  'timeline': {'2020-01-22T00:00:00Z': 0,
   '2020-01-23T00:00:00Z': 0,
   '2020-01-24T00:00:00Z': 0,
   '2020-01-25T00:00:00Z': 0,
   '2020-01-26T00:00:00Z': 0,
   '2020-01-27T00:00:00Z': 0,
   '2020-01-28T00:00:00Z': 0,
   '2020-01-29T00:00:00Z': 0,
   '2020-01-30T00:00:00Z': 0,
   '2020-01-31T00:00:00Z': 0,
   '2020-02-01T00:00:00Z': 0,
   '2020-02-02T00:00:00Z': 0,
   '2020-02-03T00:00:00Z': 0,
   '2020-02-04T00:00:00Z': 0,
   '2020-02-05T00:00:00Z': 0,
   '2020-02-06T00:00:00Z': 0,
   '2020-02-07T00:00:00Z': 0,
   '2020-02-08T00:00:00Z': 0,
   '2020-02-09T00:00:00Z': 0,
   '2020-02-10T00:00:00Z': 0,
   '2020-02-11T00:00:00Z': 0,
   '2020-02-12T00:00:00Z': 0,
   '2020-02-13T00:00:00Z': 0,
   '2020-02-14T00:00:00Z': 0,
   '2020-02-15T00:00:00Z': 0,
   '2020-02-16T00:00:00Z': 0,
   '2020-02-17T00:00:00Z': 0,
   '2020-02-18T00:00:00Z': 0,
   '2020-02-19T00:00:00Z': 0,
   '2020-02-20T00:00:00Z': 0,
   '2020-02-21T00:00:00Z': 0,
   '2020-02-22T00:00:00Z': 0,
   '2020-02-23T00:00:00Z': 0,
   '2020-02-24T00:00:00Z': 0,
   '2020-02-25T00:00:00Z': 0,
   '2020-02-26T00:00:00Z': 0,
   '2020-02-27T00:00:00Z': 0,
   '2020-02-28T00:00:00Z': 0,
   '2020-02-29T00:00:00Z': 0,
   '2020-03-01T00:00:00Z': 0,
   '2020-03-02T00:00:00Z': 0,
   '2020-03-03T00:00:00Z': 0,
   '2020-03-04T00:00:00Z': 0,
   '2020-03-05T00:00:00Z': 0,
   '2020-03-06T00:00:00Z': 0,
   '2020-03-07T00:00:00Z': 0,
   '2020-03-08T00:00:00Z': 0,
   '2020-03-09T00:00:00Z': 0,
   '2020-03-10T00:00:00Z': 0,
   '2020-03-11T00:00:00Z': 0,
   '2020-03-12T00:00:00Z': 0,
   '2020-03-13T00:00:00Z': 0,
   '2020-03-14T00:00:00Z': 0,
   '2020-03-15T00:00:00Z': 0,
   '2020-03-16T00:00:00Z': 0,
   '2020-03-17T00:00:00Z': 1,
   '2020-03-18T00:00:00Z': 3,
   '2020-03-19T00:00:00Z': 6,
   '2020-03-20T00:00:00Z': 11,
   '2020-03-21T00:00:00Z': 15,
   '2020-03-22T00:00:00Z': 25,
   '2020-03-23T00:00:00Z': 34,
   '2020-03-24T00:00:00Z': 46,
   '2020-03-25T00:00:00Z': 59,
   '2020-03-26T00:00:00Z': 77,
   '2020-03-27T00:00:00Z': 92}},
 'recovered': {'latest': 0, 'timeline': {}}}

We can get the confirmed cases with:

In [6]:
location[0]['timelines']['confirmed']['timeline']

{'2020-01-22T00:00:00Z': 0,
 '2020-01-23T00:00:00Z': 0,
 '2020-01-24T00:00:00Z': 0,
 '2020-01-25T00:00:00Z': 0,
 '2020-01-26T00:00:00Z': 0,
 '2020-01-27T00:00:00Z': 0,
 '2020-01-28T00:00:00Z': 0,
 '2020-01-29T00:00:00Z': 0,
 '2020-01-30T00:00:00Z': 0,
 '2020-01-31T00:00:00Z': 0,
 '2020-02-01T00:00:00Z': 0,
 '2020-02-02T00:00:00Z': 0,
 '2020-02-03T00:00:00Z': 0,
 '2020-02-04T00:00:00Z': 0,
 '2020-02-05T00:00:00Z': 0,
 '2020-02-06T00:00:00Z': 0,
 '2020-02-07T00:00:00Z': 0,
 '2020-02-08T00:00:00Z': 0,
 '2020-02-09T00:00:00Z': 0,
 '2020-02-10T00:00:00Z': 0,
 '2020-02-11T00:00:00Z': 0,
 '2020-02-12T00:00:00Z': 0,
 '2020-02-13T00:00:00Z': 0,
 '2020-02-14T00:00:00Z': 0,
 '2020-02-15T00:00:00Z': 0,
 '2020-02-16T00:00:00Z': 0,
 '2020-02-17T00:00:00Z': 0,
 '2020-02-18T00:00:00Z': 0,
 '2020-02-19T00:00:00Z': 0,
 '2020-02-20T00:00:00Z': 0,
 '2020-02-21T00:00:00Z': 0,
 '2020-02-22T00:00:00Z': 0,
 '2020-02-23T00:00:00Z': 0,
 '2020-02-24T00:00:00Z': 0,
 '2020-02-25T00:00:00Z': 0,
 '2020-02-26T00:00:00Z': 1,
 '2020-02-27T00:00:00Z': 1,
 '2020-02-28T00:00:00Z': 1,
 '2020-02-29T00:00:00Z': 2,
 '2020-03-01T00:00:00Z': 2,
 '2020-03-02T00:00:00Z': 2,
 '2020-03-03T00:00:00Z': 2,
 '2020-03-04T00:00:00Z': 4,
 '2020-03-05T00:00:00Z': 4,
 '2020-03-06T00:00:00Z': 13,
 '2020-03-07T00:00:00Z': 13,
 '2020-03-08T00:00:00Z': 20,
 '2020-03-09T00:00:00Z': 25,
 '2020-03-10T00:00:00Z': 31,
 '2020-03-11T00:00:00Z': 38,
 '2020-03-12T00:00:00Z': 52,
 '2020-03-13T00:00:00Z': 151,
 '2020-03-14T00:00:00Z': 151,
 '2020-03-15T00:00:00Z': 162,
 '2020-03-16T00:00:00Z': 200,
 '2020-03-17T00:00:00Z': 321,
 '2020-03-18T00:00:00Z': 372,
 '2020-03-19T00:00:00Z': 621,
 '2020-03-20T00:00:00Z': 793,
 '2020-03-21T00:00:00Z': 1021,
 '2020-03-22T00:00:00Z': 1546,
 '2020-03-23T00:00:00Z': 1924,
 '2020-03-24T00:00:00Z': 2247,
 '2020-03-25T00:00:00Z': 2554,
 '2020-03-26T00:00:00Z': 2985,
 '2020-03-27T00:00:00Z': 3417}

Now, Deaths:

In [7]:
location[0]['timelines']['deaths']['timeline'].values()

dict_values([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 6, 11, 15, 25, 34, 46, 59, 77, 92])

But how to create a `pandas.DataFrame` from this parsed data? Well, let's figure it out!

In [8]:
import pandas as pd

In [9]:
amount_of_days = len(location[0]['timelines']['confirmed']['timeline'])
days_range_list = list(range(amount_of_days))
dict_for_a_country = {
    "day": days_range_list,
    "date": list(location[0]['timelines']['confirmed']['timeline'].keys()),
    "confirmed": list(location[0]['timelines']['confirmed']['timeline'].values()),
    "deaths": list(location[0]['timelines']['deaths']['timeline'].values()),
}

dict_for_a_country

{'day': [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65],
 'date': ['2020-01-22T00:00:00Z',
  '2020-01-23T00:00:00Z',
  '2020-01-24T00:00:00Z',
  '2020-01-25T00:00:00Z',
  '2020-01-26T00:00:00Z',
  '2020-01-27T00:00:00Z',
  '2020-01-28T00:00:00Z',
  '2020-01-29T00:00:00Z',
  '2020-01-30T00:00:00Z',
  '2020-01-31T00:00:00Z',
  '2020-02-01T00:00:00Z',
  '2020-02-02T00:00:00Z',
  '2020-02-03T00:00:00Z',
  '2020-02-04T00:00:00Z',
  '2020-02-05T00:00:00Z',
  '2020-02-06T00:00:00Z',
  '2020-02-07T00:00:00Z',
  '2020-02-08T00:00:00Z',
  '2020-02-09T00:00:00Z',
  '2020-02-10T00:00:00Z',
  '2020-02-11T00:00:00Z',
  '2020-02-12T00:00:00Z',
  '2020-02-13T00:00:00Z',
  '2020-02-14T00:00:00Z',
  '2020-02-15T00:00:00Z',
  '2020-02-16T00:00:00Z',
  '2020-02-17T00:00:00Z',
  '2020-02-18T00:00:00Z',
  '2020-02-19T00:00:00Z',
  '2020-02-20T00:00:00Z',
  '2020-02-21T00:00:00Z',
  '2020-02-22T00:00:00Z',
  '2020-02-23T00:00:00Z',
  '2020-02-24T00:00:00Z',
  '2020-02-25T00:00:00Z',
  '2020-02-26T00:00:00Z',
  '2020-02-27T00:00:00Z',
  '2020-02-28T00:00:00Z',
  '2020-02-29T00:00:00Z',
  '2020-03-01T00:00:00Z',
  '2020-03-02T00:00:00Z',
  '2020-03-03T00:00:00Z',
  '2020-03-04T00:00:00Z',
  '2020-03-05T00:00:00Z',
  '2020-03-06T00:00:00Z',
  '2020-03-07T00:00:00Z',
  '2020-03-08T00:00:00Z',
  '2020-03-09T00:00:00Z',
  '2020-03-10T00:00:00Z',
  '2020-03-11T00:00:00Z',
  '2020-03-12T00:00:00Z',
  '2020-03-13T00:00:00Z',
  '2020-03-14T00:00:00Z',
  '2020-03-15T00:00:00Z',
  '2020-03-16T00:00:00Z',
  '2020-03-17T00:00:00Z',
  '2020-03-18T00:00:00Z',
  '2020-03-19T00:00:00Z',
  '2020-03-20T00:00:00Z',
  '2020-03-21T00:00:00Z',
  '2020-03-22T00:00:00Z',
  '2020-03-23T00:00:00Z',
  '2020-03-24T00:00:00Z',
  '2020-03-25T00:00:00Z',
  '2020-03-26T00:00:00Z',
  '2020-03-27T00:00:00Z'],
 'confirmed': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  2,
  2,
  2,
  2,
  4,
  4,
  13,
  13,
  20,
  25,
  31,
  38,
  52,
  151,
  151,
  162,
  200,
  321,
  372,
  621,
  793,
  1021,
  1546,
  1924,
  2247,
  2554,
  2985,
  3417],
 'deaths': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  3,
  6,
  11,
  15,
  25,
  34,
  46,
  59,
  77,
  92]}

Now we can put everything in a DataFrame:

In [10]:
df_country_data = pd.DataFrame(dict_for_a_country)
df_country_data.date = df_country_data.date.astype('datetime64[ns]') 

df_country_data

    day       date  confirmed  deaths
0     0 2020-01-22          0       0
1     1 2020-01-23          0       0
2     2 2020-01-24          0       0
3     3 2020-01-25          0       0
4     4 2020-01-26          0       0
..  ...        ...        ...     ...
61   61 2020-03-23       1924      34
62   62 2020-03-24       2247      46
63   63 2020-03-25       2554      59
64   64 2020-03-26       2985      77
65   65 2020-03-27       3417      92

[66 rows x 4 columns]

Not so complicated! Let's design a class to handle such kind of requests. Let's get the available countries and data for each country and province.

In [ ]:
all_data = covid19.getAll()

all_data

In [ ]:
country_names = list()
country_codes = list()
country_provinces = list()
for entry in all_data['locations']:
    country_name = entry['country']
    country_names.append(country_name)
    
    country_code = entry['country_code']
    country_codes.append(country_code)
    
    country_province = entry['province']
    country_provinces.append(country_province)
    
    print(f"Country name: {country_name}")
    print(f"Country code: {country_code}")
    print(f"Province: {country_province}")
    
    if country_province:
        print(f"Full region name: {country_name} ({country_province})")
        full_region_names.append(f"{country_name} ({country_province})")
    else:
        print(f"Full region name: {country_name}")
        full_region_names.append(f"{country_name}")
        
    print("**************************************\n")
    
country_database_dict = {
    "name": country_names,
    "code": country_codes,
    "province": country_provinces
}

df_available_countries = pd.DataFrame(country_database_dict)

In [ ]:
df_available_countries = df_available_countries.sort_values(by="name").reset_index(drop=True)

df_available_countries

In [ ]:
df_available_countries.to_csv("available_countries.csv", index=False)

In [ ]:
import attr

In [ ]:
# @attr.s(auto_attribs=True)
# class CountryData: